Feature/remove ocr journal
CAFECA-IO/iSunFA pull request #1051
Opened 2024-06-13 08:55 UTC by TinyMurky

### DEVELOP

- 依照db schema 更改 account, ocr, voucher, invoice等內部邏輯
- coding style優化 與 voucher的測試於merge進入 develop之後在下次pr更改

### CHECK LIST

- [Naming convention](https://github.com/CAFECA-IO/WorkGuidelines/blob/main/technology/coding-convention/naming-convention.md) verification: checked
- Coding style verification: checked
- new Library: 0
- new Class / Component: 0
- new loop: 0
- new recursive: 0
- high risk: 
    - DB Schema更改
- new sql: 
    - DB Schema更改

### UML

- none

2024-06-13 11:41 UTC, Luphia requested changes

2024-06-13 11:41 UTC, Luphia commented on prisma/seed.ts
- use '@prisma/seed_json/...' for import path

2024-06-17 02:35 UTC, TinyMurky commented on prisma/seed.ts
更改完成！

2024-06-17 02:46 UTC, Luphia approved these changes
- no bug found

2024-06-17 02:46 UTC, merged