Add aggregate line item by account
CAFECA-IO/iSunFA pull request #1290
Opened 2024-06-27 09:26 UTC by TinyMurky

### DEVELOP

- add prisma function that aggregate sum(amount) by account id

### CHECK LIST

- [x]  Use `@` in import path
- [Naming convention](https://github.com/CAFECA-IO/WorkGuidelines/blob/main/technology/coding-convention/naming-convention.md) verification: checked
- Coding style verification: checked
- new Library: 0
- new Class / Component: 0
- new loop: 0
- new recursive: 0
- high risk: 0
- new sql: 1
    - lineItem 新增groupBy操作

### UML

- none

2024-06-27 11:19 UTC, Luphia requested changes

2024-06-27 11:19 UTC, Luphia commented on src/lib/utils/repo/voucher.repo.ts
> +    const localToday = `${new Date().getFullYear()}`.padStart(4, '0') + `${new Date().getMonth() + 1}`.padStart(2, '0') + `${new Date().getDate()}`.padStart(2, '0');
- do not use new Date() consecutively.

2024-06-27 11:19 UTC, Luphia commented on src/lib/utils/repo/voucher.repo.ts
>      const localTodayStrip = localToday.replace(/\//g, '');
- no need for this line

2024-06-28 02:08 UTC, TinyMurky commented on src/lib/utils/repo/voucher.repo.ts
> +    const localToday = `${new Date().getFullYear()}`.padStart(4, '0') + `${new Date().getMonth() + 1}`.padStart(2, '0') + `${new Date().getDate()}`.padStart(2, '0');
修正完成

2024-06-28 02:08 UTC, TinyMurky commented on src/lib/utils/repo/voucher.repo.ts
>      const localTodayStrip = localToday.replace(/\//g, '');
修正完成

2024-06-28 02:39 UTC, Luphia approved these changes
- no bug found

2024-06-28 02:45 UTC, merged