Feature/beta login logic
CAFECA-IO/iSunFA pull request #2056
Opened 2024-08-14 00:37 UTC by TzuHanLiang

### DEVELOP

- [X] Description: Add Auth logic
  
#### Related Issues

- [X] Issue Number:  Link the related issue (e.g., #123)

#### Checklist

- [x] Used `@` in import paths.
- [x] Verified naming convention compliance ([Naming Convention Guidelines](https://github.com/CAFECA-IO/WorkGuidelines/blob/main/technology/coding-convention/naming-convention.md)).
- [x] Coding style verification: checked
- [x] new Library: 0
- [x] new Class / Component: 2
    - [x] InformationStatement
    - [x] TermsOfServiceAndPrivacyPolicy
- [x] new loop: 0
- [x] new recursive: 0
- [x] high risk: 0
- [x] new sql: 0

#### UML Diagrams

- None

#### Additional Notes

- Ensured all links are up-to-date.
- Conducted thorough testing on responsive design changes.
- Documented any notable considerations or edge cases addressed.

2024-08-14 14:45 UTC, Luphia requested changes

2024-08-14 14:45 UTC, Luphia commented on src/components/login_page_body/login_page_body.beta.tsx
>        // 呼叫 API 紀錄用戶已同意條款
- Annotation format does not comply

2024-08-14 14:45 UTC, Luphia commented on src/components/login_page_body/login_page_body.beta.tsx
> +    // eslint-disable-next-line no-console
- The deprecation time needs to be annotated

2024-08-14 14:45 UTC, Luphia commented on src/components/login_page_body/login_page_body.beta.tsx
> +        // eslint-disable-next-line no-console
- The deprecation time needs to be annotated

2024-08-14 14:45 UTC, Luphia commented on src/components/login_page_body/login_page_body.beta.tsx
> +        // 可能需要跳轉到錯誤頁面或顯示錯誤消息
- Annotation format does not comply

2024-08-14 14:45 UTC, Luphia commented on src/components/login_page_body/login_page_body.beta.tsx
> +    // eslint-disable-next-line no-console
- The deprecation time needs to be annotated

2024-08-14 14:45 UTC, Luphia commented on src/components/login_page_body/login_page_body.beta.tsx
> +        // 用户已同意條款，跳轉到公司選擇頁面
- The deprecation time needs to be annotated
- Annotation format does not comply

2024-08-14 14:45 UTC, Luphia commented on src/pages/api/auth/[...nextauth].ts
> +  // eslint-disable-next-line no-console
- The deprecation time needs to be annotated

2024-08-14 14:45 UTC, Luphia commented on src/pages/api/auth/[...nextauth].ts
> +        // 查找或創建新用户（不更新已有用户）
- Annotation format does not comply

2024-08-14 14:45 UTC, Luphia commented on src/pages/api/auth/[...nextauth].ts
> +      // eslint-disable-next-line no-console
- The deprecation time needs to be annotated

2024-08-14 14:45 UTC, Luphia commented on src/pages/api/auth/error.ts
> +    // eslint-disable-next-line no-console
- The deprecation time needs to be annotated

2024-08-14 14:45 UTC, Luphia commented on src/pages/api/auth/error.ts
> +    // eslint-disable-next-line no-console
- The deprecation time needs to be annotated

2024-08-14 14:45 UTC, Luphia commented on src/types/next-auth.d.ts
> +// eslint-disable-next-line @typescript-eslint/no-unused-vars
- The deprecation time needs to be annotated

2024-08-14 14:45 UTC, Luphia commented on src/pages/users/login-beta.tsx
> +    // eslint-disable-next-line no-console
- The deprecation time needs to be annotated

2024-08-14 14:45 UTC, Luphia commented on src/pages/users/login-beta.tsx
> +        // session,
- Annotation format does not comply

2024-08-15 03:44 UTC, TzuHanLiang commented
- replaced by #2067

2024-08-15 03:44 UTC, closed without merging