Feature/beta login rwd
CAFECA-IO/iSunFA pull request #2067
Opened 2024-08-14 09:39 UTC by TzuHanLiang

### DEVELOP

- Login rwd
- popup Statement
- login Logic
  
#### Related Issues

- [X] #2022 #2020 #2026 #2063

#### Checklist

- [x] Used `@` in import paths.
- [x] Verified naming convention compliance ([Naming Convention Guidelines](https://github.com/CAFECA-IO/WorkGuidelines/blob/main/technology/coding-convention/naming-convention.md)).
- [x] Coding style verification: checked
- [x] new Library: 0
- [x] new Class / Component: 0
- [x] new loop: 0
- [x] new recursive: 0
- [x] high risk: 0
- [x] new sql: 0

#### UML Diagrams

- None

#### Additional Notes

- Ensured all links are up-to-date.
- Conducted thorough testing on responsive design changes.
- Documented any notable considerations or edge cases addressed.

2024-08-14 14:55 UTC, Luphia requested changes

2024-08-14 14:55 UTC, Luphia commented on src/components/login_confirm_modal/login_confirm_modal.beta.tsx
> +  return isModalVisible ? (
- no logic in return
```typescript
const jsx = isModalVisible ? (...) : (...);
return jsx
```

2024-08-15 03:48 UTC, TzuHanLiang commented on src/components/login_page_body/login_page_body.beta.tsx
>      // eslint-disable-next-line no-console
- fixed

2024-08-15 12:18 UTC, Luphia approved these changes
- no bug found

2024-08-15 12:19 UTC, merged