Feature/mock ask api
CAFECA-IO/iSunFA pull request #2717
Opened 2024-10-04 09:29 UTC by TinyMurky

### DEVELOP

- [X] Description: Describe what you did in this PR. (e.g., "Implemented feature X to improve performance")
  
#### Related Issues

- [X] Issue Number:  #2688

#### Checklist

- [x] Used `@` in import paths.
- [x] Verified naming convention compliance ([Naming Convention Guidelines](https://github.com/CAFECA-IO/WorkGuidelines/blob/main/technology/coding-convention/naming-convention.md)).
- [x] Coding style verification: checked
- [x] new Library: 0
- [x] new Class / Component: 0
- [x] new loop: 0
- [x] new recursive: 0
- [x] high risk: 0
- [x] new sql: 0

#### UML Diagrams

- None

#### Additional Notes

- Ensured all links are up-to-date.
- Conducted thorough testing on responsive design changes.
- Documented any notable considerations or edge cases addressed.

2024-10-04 11:47 UTC, Luphia requested changes

2024-10-04 11:47 UTC, Luphia commented on src/lib/utils/zod_schema/ask_ai.ts
> +import { zodStringToNumber } from './common';
- use '@' for import path

2024-10-07 02:05 UTC, TinyMurky commented on src/lib/utils/zod_schema/ask_ai.ts
> +import { zodStringToNumber } from './common';
ok!

2024-10-07 11:46 UTC, Luphia approved these changes
- no bug found

2024-10-07 11:50 UTC, merged