Feature/real ocr
CAFECA-IO/iSunFA pull request #508
Opened 2024-05-04 15:10 UTC by TinyMurky

### DEVELOP
/company/:companyId/OCR/upload
/company/:companyId/OCR/:resultId/process_status
/company/:companyId/OCR/:resultId/result
/company/:companyId/voucher
/company/:companyId/voucher/:voucherId/process_status
/company/:companyId/voucher/:voucherId
以上api串接道AICH

### CHECK LIST

- [Naming convention](https://github.com/CAFECA-IO/WorkGuidelines/blob/main/technology/coding-convention/naming-convention.md) verification: checked
- Coding style verification: checked
- new Library: 0
- new Class / Component: 0
- new loop: 0
- new recursive: 0
- high risk: 0
- new sql: 0

2024-05-05 16:00 UTC, Luphia requested changes

2024-05-06 02:12 UTC, TinyMurky commented on src/constants/config.ts
> +export const AICH_URI = process.env.AICH_URI || 'http://localhost:3001';
修改如下
```ts
export const AICH_URI = process.env.AICH_URI as string;
```

2024-05-06 05:14 UTC, TinyMurky commented on src/lib/utils/errorCode.ts
更改完成

2024-05-06 05:14 UTC, TinyMurky commented on src/pages/api/v1/company/[companyId]/ocr/[resultId]/result.ts
> +          code: '500',
目前改成throw error的方法，從error code mapping constant

2024-05-06 05:15 UTC, TinyMurky commented on src/pages/api/v1/company/[companyId]/ocr/[resultId]/result.ts
> +        return res.status(500).json({
目前改成throw error的方法，從error code mapping constant

2024-05-06 05:15 UTC, TinyMurky commented on src/pages/api/v1/company/[companyId]/ocr/[resultId]/result.ts
>        return res.status(200).json({
目前改成從responseStatusCode.success 取出200的status code

2024-05-06 05:16 UTC, TinyMurky commented on src/pages/api/v1/company/[companyId]/voucher/index.ts
> +        code: '405',
目前改成throw error的方法，從error code mapping constant

2024-05-06 05:16 UTC, TinyMurky commented on src/pages/api/v1/company/[companyId]/voucher/index.ts
> +      res.status(405).json({
目前改成throw error的方法，從error code mapping constant

2024-05-06 05:17 UTC, TinyMurky commented on src/pages/api/v1/company/[companyId]/ocr/[resultId]/result.ts
>        return res.status(200).json({
目前改成從responseStatusCode.success 取出200的status code

2024-05-06 05:17 UTC, TinyMurky commented on src/pages/api/v1/company/[companyId]/voucher/index.ts
>        res.status(200).json({
目前改成從responseStatusCode.success 取出200的status code

2024-05-06 05:17 UTC, TinyMurky commented on src/pages/api/v1/company/[companyId]/voucher/index.ts
>          message: 'create voucher',
目前改成從responseStatusCode.success 取出200的status code

2024-05-06 05:17 UTC, TinyMurky commented on src/pages/api/v1/company/[companyId]/voucher/index.ts
>          code: '200',
目前改成從responseStatusCode.success 取出200的status code

2024-05-06 10:19 UTC, closed without merging