Feature/upload journal
CAFECA-IO/iSunFA pull request #624
Opened 2024-05-10 08:59 UTC by TzuHanLiang

### DEVELOP
- 調整 APIHandler 需要回傳 IResponseData 的 code
- 在頁面中呼叫 uploadJournal API
- 在頁面中呼叫 listJournal API
- 調整 isDisplayedJournalList UI 邏輯 @Julian0701 需要幫忙檢查一下
- 調整 getJournalDetails 並在頁面中使用API回傳數據
- 調整 EventType
- 負責 Murky #572 裡面的 STATUS_CODE 在 catch fetch error 時，將 code 設定為 STATUS_CODE.INTERNAL_SERVICE_ERROR

### CHECK LIST
- [Naming convention](https://github.com/CAFECA-IO/WorkGuidelines/blob/main/technology/coding-convention/naming-convention.md) verification: checked
- Coding style verification: checked
- new Library: 0
- new Class / Component: 0
 - new loop: 0
- new recursive: 0
- high risk: 0
- new sql: 0

2024-05-10 11:31 UTC, Luphia requested changes

2024-05-10 11:31 UTC, Luphia commented on src/components/contact_form/contact_form.tsx
- do not use eslint-disable

2024-05-10 11:31 UTC, Luphia commented on src/components/contact_form/contact_form.tsx
> +      console.log(`enmailError(${emailCode}): `, enmailError);
- require annotation for console.log

2024-05-10 11:31 UTC, Luphia commented on src/components/confirm_modal/confirm_modal.tsx
> +      console.log(`Failed to upload journal: `, codeUploadJournal, `error: `, errorUploadJournal);
- require annotation for console.log

2024-05-10 11:31 UTC, Luphia commented on src/components/camera_scanner/camera_scanner.tsx
> +      console.error('Error: ', uploadError, 'Code: ', uploadCode);
- require annotation for console.error

2024-05-13 02:16 UTC, TzuHanLiang commented on src/components/camera_scanner/camera_scanner.tsx
> +      console.error('Error: ', uploadError, 'Code: ', uploadCode);
- resolved

2024-05-13 02:16 UTC, TzuHanLiang commented on src/components/confirm_modal/confirm_modal.tsx
> +      console.log(`Failed to upload journal: `, codeUploadJournal, `error: `, errorUploadJournal);
- resolved

2024-05-13 02:16 UTC, TzuHanLiang commented on src/components/contact_form/contact_form.tsx
- resolved

2024-05-13 02:17 UTC, TzuHanLiang commented on src/components/contact_form/contact_form.tsx
> +      console.log(`enmailError(${emailCode}): `, enmailError);
- resolved

2024-05-13 03:56 UTC, Luphia approved these changes
- no bug found

2024-05-13 04:04 UTC, merged