Feature/aich interface
CAFECA-IO/iSunFA pull request #678
Opened 2024-05-14 11:19 UTC by TinyMurky

### DEVELOP
- 更改IInvoice, IVoucher, IPayment 的type
- /Users/tinymurky/Documents/mycode/iSunFA/src/components/new_journal_form/new_journal_form.tsx 內部有 `To Emily, TO Julian`字樣的是被修改的code
- /Users/tinymurky/Documents/mycode/iSunFA/src/interfaces/account.ts 有新的EventType, VoucherType,  PaymentStatusType, PaymentPeriodType
- api回傳暫時可以看 [點我](https://documenter.getpostman.com/view/29158306/2sA3JQ4f6q)

### CHECK LIST
- [Naming convention](https://github.com/CAFECA-IO/WorkGuidelines/blob/main/technology/coding-convention/naming-convention.md) verification: checked
- Coding style verification: checked
- new Library: 
- new Class / Component: 
 - new loop: 0
- new recursive: 0
- high risk: 0
- new sql: 0

2024-05-15 04:00 UTC, Luphia requested changes

2024-05-15 04:00 UTC, Luphia commented on src/interfaces/accounting_account.ts
> +import { ProgressStatus, isProgressStatus } from './account';
- use @ for import path

2024-05-15 04:00 UTC, Luphia commented on src/interfaces/invoice.ts
- use @ for import path

2024-05-15 04:00 UTC, Luphia commented on src/interfaces/account.ts
- declare enum as a constant

2024-05-16 08:48 UTC, TzuHanLiang commented on src/interfaces/invoice.ts
import { EventType, isEventType } from '@/interfaces/account'; 要改成
import { EventType, isEventType } from '@/constants/account';

2024-05-16 08:54 UTC, Luphia requested changes

2024-05-16 08:54 UTC, Luphia commented on src/constants/account.ts
- use SNAKE_CASE for constant key

2024-05-16 08:55 UTC, Luphia commented on src/interfaces/invoice.ts
- Fixed with [b130d1a](https://github.com/CAFECA-IO/iSunFA/pull/678/commits/b130d1af68fdeb3ab4abf592ed919ee6e8239904)

2024-05-16 11:17 UTC, Luphia commented on src/constants/account.ts
- ToDo later

2024-05-16 11:18 UTC, Luphia approved these changes
- no bug found

2024-05-16 11:18 UTC, merged